ccflags-y += -I$(M)/../common

obj-m := tieredvol.o
tieredvol-objs := tieredvol_core.o tieredvol_map.o tieredvol_meta.o \
                  tieredvol_log.o tieredvol_mirror.o tieredvol_wc.o \
                  tieredvol_stripe.o tieredvol_sysfs.o \
                  tieredvol_message.o tieredvol_msg_stats.o \
                  tieredvol_msg_policy.o tieredvol_msg_mirror.o \
                  tieredvol_msg_config.o
